In [1]:
#!/usr/bin/env python

#import numpy: the data structure that will handle an image
import numpy as np

#import openCV
import cv2




In [2]:
image_name = "blackwhite"

print ('read an image from file')
img = cv2.imread("images/"+image_name+".jpg")

read an image from file


In [3]:
print ('display the content of the image')
print (img)

display the content of the image
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  0   0   0]
  [  2   2   2]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  0   0   0]
  [  2   2   2]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  0   0   0]
  [  2   2   2]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  1   1   1]
  [  3   3   3]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  1   1   1]
  [  3   3   3]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  1   1   1]
  [  3   3   3]]]


In [4]:
print ('In Python, an image is stored in a numpy array. Numpy is library used for scientific computing of multi-dimensional arrays and matrices.')

print ('we can determine several features of the images using numpy array properties')
print ('type of an image type(img): %s'%type(img))
print ('size of the image img.size: %d'%img.size)

In Python, an image is stored in a numpy array. Numpy is library used for scientific computing of multi-dimensional arrays and matrices.
we can determine several features of the images using numpy array properties
type of an image type(img): <class 'numpy.ndarray'>
size of the image img.size: 1350


In [5]:
print ('length of the image (number of pixel in the vertical direction) len(img): %d'%len(img))
print ('shape of an image (length in pixe, width in pixel, number of color) img.shape (%d,%d,%d)'%img.shape)
print ('image length (also height) img.shape[0]: %d'%img.shape[0])
print ('image width img.shape[1]: %d'%img.shape[1])

length of the image (number of pixel in the vertical direction) len(img): 15
shape of an image (length in pixe, width in pixel, number of color) img.shape (15,30,3)
image length (also height) img.shape[0]: 15
image width img.shape[1]: 30


In [6]:
height, width, channels = img.shape
print ('height = %d'%height)
print ('width = %d'%width)
print ('channels = %d'%channels)

height = 15
width = 30
channels = 3


In [7]:
print ('number of colors per pixel img.shape[2]: %d'%img.shape[2])
print ('number of pixels: %d'%(img.shape[0]*img.shape[1]))

number of colors per pixel img.shape[2]: 3
number of pixels: 450


In [8]:
print ('type of the image img.dtype: %s'%img.dtype)
print ('sub-image at row [10] (img[10])')
print (img[10])

type of the image img.dtype: uint8
sub-image at row [10] (img[10])
[[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [254 254 254]
 [255 255 255]
 [255 255 255]
 [254 254 254]
 [255 255 255]
 [243 243 243]
 [ 76  76  76]
 [  1   1   1]
 [ 18  18  18]
 [  1   1   1]
 [  0   0   0]
 [  1   1   1]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  1   1   1]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  2   2   2]]


In [9]:
print ('shape of sub-image at row [0] (img[10].shape)')
print (img[10].shape)

shape of sub-image at row [0] (img[10].shape)
(30, 3)


In [10]:
print ('pixel at raw 10 and column 5 (img[10, 5])')
print (img[10, 5])
print (img[10] [5])

pixel at raw 10 and column 5 (img[10, 5])
[255 255 255]
[255 255 255]


In [11]:
print ('pixel at raw 0 and column 0 (img[0, 0])')
print (img[0, 0])
print (img[0] [0])

pixel at raw 0 and column 0 (img[0, 0])
[255 255 255]
[255 255 255]


In [12]:
print ('you can see a single channel in the image, for example only the first channel')
print (img[:, :, 0])

you can see a single channel in the image, for example only the first channel
[[255 255 255 255 255 255 255 255 255 255 255 255 254 255 243  76   1  18
    1   0   1   0   0   0   0   1   0   0   0   2]
 [255 255 255 255 255 255 255 255 255 255 255 255 254 255 243  76   1  18
    1   0   1   0   0   0   0   1   0   0   0   2]
 [255 255 255 255 255 255 255 255 255 255 255 255 254 255 243  76   1  18
    1   0   1   0   0   0   0   1   0   0   0   2]
 [255 255 255 255 255 255 255 255 255 255 255 255 254 255 243  76   1  18
    1   0   1   0   0   0   0   1   0   0   0   2]
 [255 255 255 255 255 255 255 255 255 255 255 255 254 255 243  76   1  18
    1   0   1   0   0   0   0   1   0   0   0   2]
 [255 255 255 255 255 255 255 255 255 255 255 255 254 255 243  76   1  18
    1   0   1   0   0   0   0   1   0   0   0   2]
 [255 255 255 255 255 255 255 255 255 255 255 255 254 255 243  76   1  18
    1   0   1   0   0   0   0   1   0   0   0   2]
 [255 255 255 255 255 255 255 255 255 255 255 2